### PR TITLE
Merge SVN and fix(UDPEndPoint): add public modifier to the getSocket method

### PR DESCRIPTION
**Pull request by Joge97**
Hello,

I needed to access the datagram socket of the UDP End point. So i added the public modifier to the getSocket method. I thought others could find this useful too and I decided to make a pull request.

I hope you are going to integrate it.

Regards Joge97

### CODE REVIEW

**Comment by JohannesBuchner** [comment]
Could you check upstream? And maybe merge?

**Comment by Joge97** [comment]
What do you mean with check upstream and merge? I don´t have the rights to merge this pull request.

**Comment by JohannesBuchner** [comment]
This repo is pretty outdated. What you want may be already implemented at  http://udt-java.sf.net . 

If you have extra time, you could update your fork with the commits from that repo, so that there is a recent version on github.

**Comment by Joge97** [comment]
I will merge it in a few days.

**Comment by Joge97** [comment]
I have merged the svn repository without the last commit (which is not working). Can you now merge this pull request?

**Comment by JohannesBuchner** [comment]
Thank you! Seems like upstream has been dead for a few years :(

**Pull request merged**
